### ISSUE TITLE
Adjust the color of headset depends on his color (with ip adress) 

### ISSUE THREAD

**Issue by nautuan** [project-SIMPLE/simple.webplatform#22]
in the future, according to the headset ip adress , display the appropriate headset image, watch below

**Comment by nautuan** [comment]
![Gama_helmet_blue](https://github.com/user-attachments/assets/411c73d0-0be9-49fc-b951-f7b57a7d3aab)
![Gama_helmet_Yellow](https://github.com/user-attachments/assets/ac27b633-e6df-4107-9e34-ee20f72ed7aa)
![Gama_helmet_red](https://github.com/user-attachments/assets/c7955aff-1334-43c5-babb-6d0429aab8ac)
![Uploading Gama_helmet_green.png…]()

**Comment by RoiArthurB** [comment]
This is IP based, as you receive all the headset information (including the IP address) it's something you can set in the front interface :)
