### ISSUE TITLE
BUG: Dotenv file isn't read anymore

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/simple.webplatform#25]
Since the mid-migration of the backend on TypeScript, the file `./src/index.ts` doesn't read value set in `.env` file anymore...

This seems to be as it doesn't support it in the same manner than js (ie. with the use of `process.env.X` but require the use of the `dotenv` library).

**Comment by nautuan** [comment]
issue fixed

**Comment by RoiArthurB** [comment]
@nautuan I think you did revert your fix.. Can you re-test it and close this issue when fixed please ? :)
